language: node_js
node_js:
  - "10"
cache:
  directories:
    - "~/.npm"
env:
  global:
    - TRUNK_BRANCH="master"
    - secure: kxD6tQ1unLS2HZjneygOxPlCpKDvR39e1ZbUrxK9JxDpLqxN5YQ9MN1eoqd7XSKeInR5DA9xWPV6lqPPOwTsVq+xX6YX0vmWI/Qa5ltvVZU7EEGtNphyPwEGCJuYShLqNi/ZHIRx86jnxq2mhOhlOKspFdd05n2pT7QgXqJSyvCKmtPQtmfDj+oo/Owk/8FKneSbzF8sIQ9XlmdupqymM/LP5OjFLFxDs7u+cLgqpKPoYwhS7AA9QzDddW+hvGaSFfQ6FOySZH/b0H3+URJz1A5qkzYDOKv+sN8x1hAT//8jtwwsL9T+lk/Ze24fzAgDj4X3vZ2WFXy25BRNVJjGSHSAPw33EM5/NPR0P4Q08JsP2LWwvbgdQ9pYMeb4qSvRcZK5lV4XoqZmXaffI99aD7YWB5AYFDN1v64JIGjpAm9KbqQh49SuOzQGJDa4WIiaFD/nKYoAll8EQIFi8kwH0pGHtVwluIjMwPCgjf5NRBar+o+W33Q3cC0aLMZHvPkxQxMNBGg7tNrHZGS4uR30LlbCa1e74m9ARh1k+CcJmDeJ2IogfZu8KSiuwr0eWZFDYQwLgujMnEF2EnwA3hMI10BVcH9/9N4oHxR5tSkwFXZtKn6NkBLu70v1QYwzeSXKD6cB5HTGnY1FoEE2xhoZmDU8VzNdeNhVoQy5snilKZ4=
    - secure: a7TV4/i5CYC5dH8SDQEN2pEDtiKp/DuOBZ1a4HtbrV5pAoocwujAscS27cPik/F0oryiOi7PMbEH+TE8nAgxOPrJ11KwD3SJUKfar0alf4QTtC5eNI5CgCVkDdjyN9hzB3bm9NIErdc3lKHwRHoz6UYbLM4HjIU+DRaI4rPGOW7P43Me1WMDVAIMgRhNel/J+IcDfZ4eoYGIcsdRklNPTi00GBAK9T/y7qc8+nvED/gm1VbVeFW+0EJyXbBcfwEEHtBs66ZvgoRS6ceF0oUh1sW/BMTKDdTxLyXpESj5OYAq2XbuoxS/pcuSSWF4trJdw01X+bDM1vb12hwwhvoRRdej+1lU4V4DQGFQmyBvaHj4hnes0AGTjv2zLdTqYqrDjGJ2Ly/W5Ttft6gBKkYFqHO+76NqLUq3CzruWKgCRhquJYhxrF+QqVe40r592Fct78D6XxIjfGWrku8G0WNhUc5KSzz4qkveVXxi9ZyWkgLKIBQov3Gh52TiW6mucZWpDjd1t7M/4tZEf4Ci/uF/Qt6pfIE65mgHDTJvOiAnHDqVFIqKkowPUne7K7Kz8Q8Tml9Wphs3i+TNMPeFmH2D6u+MyRxegapS+ysFQO2PbPHovbMNHFukHEHYQI3/W19ETtvOXzS2JtogPm/6etdmzD+D0htl6tISAKWzlvU97JU=
install:
  - npm ci
script: skip
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: release
      if: branch = env(TRUNK_BRANCH) AND type = push
      script:
        - source ./ci/prepare-release.sh || travis_terminate 1
        - npm run release || travis_terminate 1
        - git push --follow-tags origin $TRAVIS_BRANCH || travis_terminate 1
        - npm run github-release || travis_terminate 1
        - npm publish || travis_terminate 1
